title: Pritham Raaj Kishore Anand
description: Seeking to leverage and utilize my familiarity with Data and Machine learning concepts to streamline processes and increase efficiency. Driven and a quick learner with excellent communication skills.
show_downloads: true
theme: jekyll-theme-minimal
